sudo: required

language: java

services:
  - docker

matrix:
  include:
# EOL
#    - env: CPEH_VERSION=luminous
#      before_install:      
#        - docker pull ceph/daemon@sha256:174f26cf8752c20da2a69da461c46acd34f1d9a3b81f0761011c015178697346
#        - docker run -d -p 80:80 -v /etc/cephl/:/etc/ceph/ -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq -e  RGW_CIVETWEB_PORT=80  -e NETWORK_AUTO_DETECT=4 --name rgwl ceph/daemon@sha256:174f26cf8752c20da2a69da461c46acd34f1d9a3b81f0761011c015178697346 demo
#        - sleep 30
    - env: CPEH_VERSION=mimic
      before_install:
        - docker pull ceph/daemon:v3.2.8-stable-3.2-mimic-centos-7
        - docker run -d -p 80:80 -v /etc/cephm/:/etc/ceph/ -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq -e  RGW_CIVETWEB_PORT=80  -e NETWORK_AUTO_DETECT=4 --name rgwm ceph/daemon:v3.2.8-stable-3.2-mimic-centos-7 demo
        - timeout 60 bash -c "until docker logs rgwm &> rgwm.log && grep SUCCESS rgwm.log; do sleep 1; done" 
        - docker ps
        - cat rgwm.log
        - echo -e 'GET / HTTP/1.1\r\nHost:localhost\r\n\r\n' | nc localhost 80
    - env: CPEH_VERSION=nautilus
      before_install:
        - docker pull ceph/daemon:v4.0.1-stable-4.0-nautilus-centos-7
        - docker run -d -p 80:80 -v /etc/cephn/:/etc/ceph/ -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq -e  RGW_CIVETWEB_PORT=80  -e NETWORK_AUTO_DETECT=4 --name rgwn ceph/daemon:v4.0.1-stable-4.0-nautilus-centos-7 demo
        - timeout 60 bash -c "until docker logs rgwn &> rgwn.log && grep SUCCESS rgwn.log; do sleep 1; done" 
        - docker ps
        - cat rgwn.log
        - echo -e 'GET / HTTP/1.1\r\nHost:localhost\r\n\r\n' | nc localhost 80
    - env: CPEH_VERSION=octopus
      before_install:
        - docker pull ceph/daemon:v5.0.4-stable-5.0-octopus-centos-8
        - docker run -d -p 80:80 -v /etc/cephn/:/etc/ceph/ -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq -e  RGW_CIVETWEB_PORT=80  -e NETWORK_AUTO_DETECT=4 --name rgwo ceph/daemon:v5.0.4-stable-5.0-octopus-centos-8 demo
        - timeout 60 bash -c "until docker logs rgwo &> rgwo.log && grep SUCCESS rgwo.log; do sleep 1; done" 
        - docker ps
        - cat rgwo.log
        - echo -e 'GET / HTTP/1.1\r\nHost:localhost\r\n\r\n' | nc localhost 80
        
install: mvn install -Dgpg.skip=true

after_failure:
  - cat target/surefire-reports/*.txt
